### PR TITLE
Add shells completions

### PR DESCRIPTION
**Pull request by Cronos87**
Issue #8 + updated modules.

### CODE REVIEW

**Review by mightymatth — COMMENTED** [review]
should files in `contrib/completions` be commited?

**Comment by Cronos87** [comment]
I suppose yes. But I don't know GoReleaser well. Maybe it can do this automatically 🤔

What do you think?

**Comment by mightymatth** [comment]
> I suppose yes. But I don't know GoReleaser well. Maybe it can do this automatically 🤔
> 
> What do you think?

Me neither. I'll take a look at this and see whether it can be done in build-time. 

And thanks a lot for your contribution! :)

**Comment by Cronos87** [comment]
Great! Thank you!

You're welcome 😉 I have some other ideas I will submit too.

**Comment by Cronos87** [comment]
I will close the pull request and make a new one without the contrib directory. Like this if you need it I can commit it later.
And in any case I pushed my feature in master from my fork... which is not a good way to do.

Is that okay for you?

**Pull request closed without merging**
